param(
  [string]$Python = "python",
  [string]$OutputRoot = "runs\submission_cases",
  [string]$ArtifactRoot = "submission_artifacts\cases"
)

$ErrorActionPreference = "Stop"

$root = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
$manifestPath = Join-Path $root "examples\batch_manifest_5cases.json"
$outputPath = Join-Path $root $OutputRoot
$artifactPath = Join-Path $root $ArtifactRoot

function Write-Utf8NoBom {
  param(
    [string]$Path,
    [string]$Value
  )
  $encoding = New-Object System.Text.UTF8Encoding($false)
  [System.IO.File]::WriteAllText($Path, $Value, $encoding)
}

if (Test-Path $outputPath) {
  Remove-Item -LiteralPath $outputPath -Recurse -Force
}
if (Test-Path $artifactPath) {
  Remove-Item -LiteralPath $artifactPath -Recurse -Force
}
New-Item -ItemType Directory -Force -Path $outputPath | Out-Null
New-Item -ItemType Directory -Force -Path $artifactPath | Out-Null

$env:PYTHONPATH = Join-Path $root "src"
Push-Location $root
try {
  & $Python -m mineru_data_agent.cli batch --manifest $manifestPath --out $outputPath --profile auto
  if ($LASTEXITCODE -ne 0) {
    throw "submission case batch failed with exit code $LASTEXITCODE"
  }
} finally {
  Pop-Location
}

$manifest = Get-Content -Raw -Encoding UTF8 -LiteralPath $manifestPath | ConvertFrom-Json
$reportPath = Join-Path $outputPath "batch_report.json"
$report = Get-Content -Raw -Encoding UTF8 -LiteralPath $reportPath | ConvertFrom-Json
$caseSummaries = @()

for ($i = 0; $i -lt $report.items.Count; $i++) {
  $item = $report.items[$i]
  $task = $manifest.tasks[$i]
  $caseId = if ($item.id) { [string]$item.id } else { "case_$($i + 1)" }
  $caseDir = Join-Path $artifactPath $caseId
  New-Item -ItemType Directory -Force -Path $caseDir | Out-Null

  $inputSource = if ($item.resolved_input) { [string]$item.resolved_input } else { Join-Path (Split-Path $manifestPath -Parent) ([string]$task.input) }
  Copy-Item -LiteralPath $inputSource -Destination (Join-Path $caseDir ("input" + [IO.Path]::GetExtension($inputSource))) -Force

  foreach ($fileName in @("result.json", "trace.json", "summary.md")) {
    $source = Join-Path ([string]$item.output_dir) $fileName
    if (Test-Path $source) {
      Copy-Item -LiteralPath $source -Destination (Join-Path $caseDir $fileName) -Force
    }
  }

  $retrievalSource = Join-Path ([string]$item.output_dir) "retrieval"
  if (Test-Path $retrievalSource) {
    Copy-Item -LiteralPath $retrievalSource -Destination (Join-Path $caseDir "retrieval") -Recurse -Force
  }

  $resultPath = Join-Path $caseDir "result.json"
  $qualityStatus = [string]$item.quality_status
  $qualityScore = [int]$item.quality_score
  $sectionCount = 0
  $tableCount = 0
  $keyValueCount = 0
  $semanticSignalText = "not available"
  if (Test-Path $resultPath) {
    $result = Get-Content -Raw -Encoding UTF8 -LiteralPath $resultPath | ConvertFrom-Json
    $sectionCount = @($result.extracted.sections).Count
    $tableCount = @($result.extracted.tables).Count
    $keyValueCount = @($result.extracted.key_values).Count
    $semanticSignalText = "dates=$(@($result.extracted.semantic_signals.dates).Count), recommendations=$(@($result.extracted.semantic_signals.recommendations).Count), anomalies=$(@($result.extracted.semantic_signals.anomaly_lines).Count)"
  }

  $readme = @(
    "# $caseId",
    "",
    "- Task: $($task.task)",
    "- Profile: $($task.profile)",
    "- Status: $($item.status)",
    "- Quality: $qualityStatus ($qualityScore/100)",
    "- Sections: $sectionCount",
    "- Tables: $tableCount",
    "- Key-values: $keyValueCount",
    "- Semantic signals: $semanticSignalText",
    "- Required evidence: result.json, trace.json, summary.md, retrieval/",
    ""
  ) -join "`n"
  Write-Utf8NoBom -Path (Join-Path $caseDir "README.md") -Value $readme

  $caseSummaries += [pscustomobject]@{
    id = $caseId
    task = [string]$task.task
    profile = [string]$task.profile
    status = [string]$item.status
    quality_status = $qualityStatus
    quality_score = $qualityScore
    sections = $sectionCount
    tables = $tableCount
    key_values = $keyValueCount
  }
}

Copy-Item -LiteralPath $reportPath -Destination (Join-Path $artifactPath "batch_report.json") -Force
Write-Utf8NoBom -Path (Join-Path $artifactPath "artifact_index.json") -Value ($caseSummaries | ConvertTo-Json -Depth 6)

$indexLines = @(
  "# Submission Case Artifacts",
  "",
  "These artifacts are generated by scripts/run_submission_cases.ps1 from examples/batch_manifest_5cases.json.",
  "Each case directory contains the input fixture, result.json, trace.json, summary.md, and retrieval export files.",
  "",
  "| Case | Profile | Status | Quality | Sections | Tables | Key-values |",
  "| --- | --- | --- | ---: | ---: | ---: | ---: |"
)
foreach ($case in $caseSummaries) {
  $indexLines += "| $($case.id) | $($case.profile) | $($case.status) | $($case.quality_score) | $($case.sections) | $($case.tables) | $($case.key_values) |"
}
$indexLines += ""
Write-Utf8NoBom -Path (Join-Path $artifactPath "README.md") -Value ($indexLines -join "`n")

Write-Output "Generated submission case artifacts at $ArtifactRoot"
